autorage/urls.py
from django.urls import path
from . import views

app_name = "autorage"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('make_publication', views.MakePublicationView.as_view(), name='make_publication'),
    path('publications', views.PublicationsView.as_view(), name='publications'),
    path('registration', views.RegistrationView.as_view(), name='registration'),
    path('authentication', views.AuthenticationView.as_view(), name='authentication'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    # path('car/<int:pk>', views.CarView.as_view(), name="car"),
    path('car/<int:pk>', views.carView, name="car"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

import website.settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("autorage.urls"))
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

autorage/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class ModuleType(models.Model):
    """Модель типа модуля"""
    type = models.CharField(max_length=64)

    def __str__(self):
        return self.type


class Module(models.Model):
    """Модель модуля машины"""

    type = models.ForeignKey(ModuleType, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    description = models.TextField()
    photo = models.ImageField(upload_to="modules/%Y/%m/%d/")

    def __str__(self):
        return f"{self.type}: {self.name}"


# class User(models.Model):
#     """Модель аккаунта пользователя"""

#     login = models.CharField(max_length=32)
#     password = models.CharField(max_length=32)
#     photo = models.ImageField(upload_to="users")
#     reg_date = models.DateTimeField(auto_now_add=True)


class CarBrand(models.Model):
    """Модель бренда автомобиля"""

    brand = models.CharField(max_length=31)

    def __str__(self):
        return self.brand


class CarModel(models.Model):
    """Модель модели автомобиля"""

    model = models.CharField(max_length=31)

    def __str__(self):
        return self.model


class Car(models.Model):
    """Модель статьи об автомобиле"""

    brand = models.ForeignKey(
        CarBrand,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Производитель',
    )
    model = models.ForeignKey(
        CarModel,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Модель',
    )
    description = models.TextField(
        blank=True,
        verbose_name='Описание',
    )  # description
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    update_date = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления'
    )
    modules = models.ManyToManyField(
        Module,
        verbose_name='Установленные модули'
    )
    photo = models.ImageField(
        upload_to="cars/%Y/%m/%d/",
        verbose_name='Фото'
        )

    # owner = models.ForeignKey(User, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return f"{self.brand} {self.model}"

    def get_absolute_url(self):
        return reverse('autorage:car', kwargs={'pk': self.pk})

    class Meta:

        ordering = ["-pub_date", "?"]


class Comment(models.Model):
    """Модель комментария пользователя к статье"""

    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.CharField(max_length=256)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


# class CarPhoto(models.Model):
#     """Модель фотографии автомобиля"""

#     car = models.ForeignKey(Car, on_delete=models.CASCADE)
#     photo = models.ImageField(upload_to="cars/%Y/%m/%d/")


# class ModulePhoto(models.Model):
#     """Модель фотографии модуля"""

#     module = models.ForeignKey(Module, on_delete=models.CASCADE)
#     photo = models.ImageField(upload_to="modules/%Y/%m/%d/")

autorage/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

# class AddPostForm(forms.Form):
#     brand = forms.ModelChoiceField(
#         queryset=CarBrand.objects.all(),
#         label="Производитель",
#     )
#     model = forms.ModelChoiceField(
#         queryset=CarModel.objects.all(),
#         label="Модель",
#     )
#     description = forms.CharField(
#         widget=forms.Textarea(
#             attrs={'cols': 60, 'rows':10}
#         ),
#         label='Описание'
#     )
#     modules = forms.ModelMultipleChoiceField(
#         queryset=Module.objects.all(),
#         widget=forms.CheckboxSelectMultiple
#     )
#     image = forms.ImageField(
#         label="Изображение"
#     )

class AddPostForm(forms.ModelForm):

    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['brand'].empty_label = 'Выберите производителя'
        self.fields['model'].empty_label = 'Выберите модель'

        self.fields['brand'].widget.attrs.update({'class':'input-box'})
        self.fields['model'].widget.attrs.update({'class':'input-box'})
        self.fields['description'].widget.attrs.update({'class':'input-box'})
        self.fields['modules'].widget.attrs.update({'class':'input-box'})
        self.fields['photo'].widget.attrs.update({'class':'input-box'})

    class Meta:
        model = Car
        fields = ['brand', 'model', 'description', 'modules', 'photo']
        widgets = {
            'description': forms.Textarea(
                attrs={
                    'cols': 60,
                    'rows': 14,
                }
            )
        }

class AutorageCreateUserForm(UserCreationForm):

    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(
            attrs={
                'class': 'input-box'
            }
        )
    )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.TextInput(
            attrs={
                'class': 'input-box'
            }
        )
    )
    password2 = forms.CharField(
        label='Подтвердите пароль',
        widget=forms.TextInput(
            attrs={
                'class': 'input-box'
            }
        )
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class AutorageAuthenticationForm(AuthenticationForm):

    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(
            attrs={
                'class': 'input-box'
            }
        )
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.TextInput(
            attrs={
                'class': 'input-box'
            }
        )
    )

class AddCommentForm(forms.Form):
    
    text = forms.CharField(
        label='',
        max_length=255,
        widget=forms.Textarea(
            attrs={
            'cols': 30,
            'rows': 3,
            'class': 'input-box'
            }
        )
    )

autorage/views.py
from typing import Any, Dict
from django.urls import reverse_lazy
from .models import Car, Comment
from django.views import generic
from .utils import menu_titles, DataMixin
from .forms import *
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpRequest
from autorage.utils import menu_titles
import re


class IndexView(DataMixin, generic.ListView):
    """Представление главной страницы"""

    model = Car
    template_name = 'autorage/index.html'
    context_object_name = 'pictures'
    ordering = '?'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        default_context = self.get_menu_context(self.request.user, selected_title='')
        return dict(list(context.items()) + list(default_context.items()))


class CarView(DataMixin, generic.DetailView):
    """Представление одной публикации"""

    model = Car
    template_name = "autorage/car.html"
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        this_car = self.get_object()

        context = super().get_context_data(**kwargs)
        context['title'] = this_car
        context['comments'] = Comment.objects.filter(car=this_car)
        default_context = self.get_menu_context(self.request.user)
        return dict(list(context.items()) + list(default_context.items()))
    

def carView(request: HttpRequest, pk: int):

    car = Car.objects.get(pk=pk)

    context = {}
    context['menu_titles'] = menu_titles.copy()
    context['is_auth'] = request.user.is_authenticated
    context['selected_title'] = 'none'
    context['car'] = car
    context['comments'] = Comment.objects.filter(car=car)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            
            print(form.cleaned_data)
            text = form.cleaned_data['text']
            author = request.user
            
            try:
                Comment.objects.create(
                    text=text,
                    author=author,
                    car=car
                )
            except Exception as e:
                form.add_error(None, "Публикация не создана из-за возникшей ошибки")
                print(f"Ошибка: {e}")
            else:
                return redirect(car)

        else:
            print(form.errors)
    else:
        form = AddCommentForm()

    context['comment_form'] = form

    return render(
        request,
        'autorage/car.html',
        context
    )

class MakePublicationView(DataMixin, generic.CreateView):
    """Представление страницы создания публикации"""

    template_name = 'autorage/add_post.html'
    form_class = AddPostForm
    success_url = reverse_lazy('autorage:index')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)
        context['title'] = 'Опубликовать'
        default_context = self.get_menu_context(self.request.user, selected_title='make_publication')
        return dict(list(context.items()) + list(default_context.items()))


class PublicationsView(DataMixin, generic.ListView):
    """Представление страницы с публикациями"""

    model = Car
    template_name = 'autorage/posts.html'
    context_object_name = 'cars'
    extra_context = {
        'title': 'Публикации'
    }

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)
        default_context = self.get_menu_context(self.request.user, selected_title='publications')
        return dict(list(context.items()) + list(default_context.items()))

class RegistrationView(DataMixin, generic.CreateView):
    """Представление страницы регистрации"""

    form_class = AutorageCreateUserForm
    template_name = 'autorage/registration.html'
    success_url = reverse_lazy('autorage:index')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        default_context = self.get_menu_context(self.request.user, selected_title='registration')
        return dict(list(context.items()) + list(default_context.items()))

class AuthenticationView(DataMixin, LoginView):
    """Представление страницы входа в профиль"""

    form_class = AutorageAuthenticationForm
    template_name = 'autorage/authentication.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)
        context['title'] = 'Войти'
        default_context = self.get_menu_context(self.request.user, selected_title='authentication')
        return dict(list(context.items()) + list(default_context.items()))
    
    def get_success_url(self) -> str:
        return reverse_lazy('autorage:index')

class ProfileView(DataMixin, generic.DetailView):
    """Представление страницы профиля"""

    template_name = 'autorage/profile.html'
    model = User
    context_object_name = 'user'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        default_context = self.get_menu_context(self.request.user, selected_title='profile')
        return dict(list(context.items()) + list(default_context.items()))

autorage/templates/autorage/add_post.html
{% extends 'autorage/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div>
    <div>
        <h1>Добавить публикацию</h1>
    </div>
    <div>
        <form action="{% url 'autorage:make_publication' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="input-button">Опубликовать</button>
        </form>
    </div>
</div>

{% endblock %}

autorage/templates/autorage/authentication.html
{% extends 'autorage/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="input-button">Войти</button>
	</form>
</div>
{% endblock %}

autorage/templates/autorage/base.html
{% include 'autorage/header.html' %}

{% include 'autorage/main_menu_panel.html' %}
<div class="wrapper">
	{% block content %}
	{% endblock %}
</div>

{% include 'autorage/footer.html' %}

autorage/templates/autorage/car.html
{% extends 'autorage/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="container car-container car-header">
				<h1>{{ car }}</h1>
				<div class="container car-photo">
					<img src="{{ car.photo.url }}" alt="Тут должна быть машина"/>
				</div>
			</div>
			<div class="container car-container car-description">
				{{ car.description | linebreaks }}
			</div>
		</div>
		<div class="col car-container ">
			<div class="containercar-comments">
				<P><h3>Комментарии</h3></P>
				{% if is_auth %}
				<form action="{% url 'autorage:car' pk=car.pk %}" method="post">
					{% csrf_token %}
					{{ comment_form|crispy }}
					<button type="submit" class="input-button">Комментировать</button><br>
				</form>
				{% else %}
				<h3>Войдите, чтобы оставить комментарий</h3>
				{% endif %}
				{% if comments %}
				<ul>
					{% for c in comments %}
					<div>
						<li>{{ c.author }} | {{ c.text }}<br></li>
					</div>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="row text-center">
		<div class="col">
			<div class="container car-container car-modules">
				{% for module in car.modules.all %}
					<div class="row module-container">
						<div class="col">
							<div class="car-photo">
								<img class="module-photo" src="{{module.photo.url}}" alt="Тут должен быть модуль"/>
							</div>
						</div>
						<div class="col">
							<h4>{{module.type}}: {{module.name}}</h4>
							<p>{{module.description | linebreaks}}</p>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

{% endblock %}

autorage/templates/autorage/dateline.html
<div class="MainMenu" style="background-color: rgba(53, 53, 53, 0.7);">
	<p style="margin: 20px 0 20px 0;"><h1>today is {% now "jS F Y" %}</h1></p>
</div>

autorage/templates/autorage/footer.html
{% load static %}
	<script src="{% static 'autorage/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

autorage/templates/autorage/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'autorage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'autorage/css/style.css' %}">
    <title>{{title}}</title>
</head>
<body>

autorage/templates/autorage/index.html
{% extends 'autorage/base.html' %}

{% block content %}
<div>
    <div style="margin: 50px 0 0 0; display: flex; justify-content: center;">
        <h1 style="color: var(--blue)">Добро пожаловать на наш сайт</h1>
    </div>
    <div class="MainMenu">
        <ul>
{% for p in pictures %}
            <li style="margin: 5px 0 0 5px;"><img src="{{ p.photo.url }}" alt="car"></li>
{% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

autorage/templates/autorage/main_menu_panel.html
<header>
    <div class="MainMenu">
         <div>
        <h1>AUTORAGE</h1>
      </div>
      <div>
        <ul>
{% for title, text in menu_titles.items %}
  {% if title == selected_title %}
          <li class="MenuTitleSelected"><a href="/{{title}}"><b>{{text}}</b></a></li>
  {% else %}
          <li><a href="/{{title}}"><b>{{text}}</b></a></li>
  {% endif %}
{% endfor %}
{% if is_auth %}
  {% if selected_title == 'profile' %}
          <li class="MenuTitleSelected"><a href="/profile/{{ user.pk }}"><b>Профиль</b></a></li>
  {% else %}
          <li><a href="/profile/{{ user.pk }}"><b>Профиль</b></a></li>
  {% endif %}
{% else %}
{% if selected_title == 'authentication' %}
          <li class="MenuTitleSelected"><a href="/authentication"><b>Войти</b></a></li>
  {% else %}
          <li><a href="/authentication"><b>Войти</b></a></li>
  {% endif %}
  {% if selected_title == 'registration' %}
          <li class="MenuTitleSelected"><a href="registration"><b>Регистрация</b></a></li>
  {% else %}
          <li><a href="/registration"><b>Регистрация</b></a></li>
  {% endif %}
{% endif %}
        </ul>
      </div>
    </div>
</header>

autorage/templates/autorage/posts.html
{% extends 'autorage/base.html' %}

{% block content %}
<div>
    <uls style="list-style-type: none;">
{% if cars %}
{% for car in cars %}
        <li>
            <div>
                <a href="{% url 'autorage:car' car.pk %}">
                    <span><img src="{{ car.photo.url }}" alt="Тут должна быть машина"/></span>
                    <h2>{{car}}</h2>
                </a>
            </div>
        </li>
{% endfor %}
{% else %}
        <li><h1>ТУТ ПОКА НИЧЕГО НЕТ, НО ДОЛЖНЫ БЫТЬ ПУБЛИКАЦИИ</h1></li>
{% endif %}
    </ul>
</div>
{% endblock %}

autorage/templates/autorage/profile.html
{% extends 'autorage/base.html' %}

{% block content %}
<div class="profile">
	{{ user.username }}<br>
	{{ user.date_joined }}
</div>
{% endblock %}

autorage/templates/autorage/registration.html
{% extends 'autorage/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="input-button">Регистрация</button>
	</form>
</div>
{% endblock %}